title: Mohammad Rafieian's Personal Website
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal website. I'm a PhD candidate at The University of Texas at Dallas.
  Here, you'll find my research, projects, and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://<yourusername>.github.io" # the base hostname & protocol for your site

# Build settings
theme: minima

# Permalinks for pretty URLs
permalink: /:categories/:title/

# Author information
author:
  name: "Mohammad Rafieian"
  email: "your.email@example.com" # replace with your actual email

# Social media links (Optional)
social_links:
  twitter: your_twitter_username
  linkedin: your_linkedin_profile_url
  github: https://github.com/<yourusername>

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Enable Disqus comments (Optional)
# Replace 'your-disqus-shortname' with your actual Disqus shortname
# Uncomment if you want to enable comments
# disqus:
#   shortname: your-disqus-shortname

# Google Analytics (Optional)
# Uncomment and replace 'UA-XXXXXXX-X' with your Google Analytics tracking ID
# google_analytics: UA-XXXXXXX-X

# Exclude these files from production builds
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter_opts:
    block:
      line_numbers: false
