title: "Mohammad Rafieian"
name: "Mohammad Rafieian"
description: "PhD Candidate in Software Engineering at UTD"
remote_theme: "academicpages/academicpages.github.io"
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# include:
#   - _pages


# # Navigation
# header_pages:
#   - index.md
#   - _pages/about.md
#   - _pages/research.md
#   - _pages/projects.md
#   - _pages/contact.md

# Author Info
author:
  name   : "Mohammad Rafieian"
  avatar : "/assets/profile.jpg"
  bio    : "PhD Candidate in Software Engineering at The University of Texas at Dallas"
  location : "Dallas, Texas"
  email  : "Mohammad.Rafieian@utdallas.edu"
  github : "mohpydev"
  linkedin : "mohammad-rafieian"
  scholar : "YOUR_GOOGLE_SCHOLAR_ID" # can add later

# Footer Social Icons
footer_links:
  - title: "Email"
    url: "mailto:Mohammad.Rafieian@utdallas.edu"
    icon: fas fa-envelope
  - title: "GitHub"
    url: "https://github.com/mohpydev"
    icon: fab fa-github
  - title: "LinkedIn"
    url: "https://linkedin.com/in/mohammad-rafieian"
    icon: fab fa-linkedin
  - title: "Google Scholar"
    url: "https://scholar.google.com/citations?user=YOUR_ID"
    icon: fas fa-graduation-cap

# Defaults for pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true