title: Mohammad Rafieian's Personal Website
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal website. I'm a PhD candidate at The University of Texas at Dallas.
  Here, you'll find my research, projects, and more.
theme: jekyll-theme-minimal
